name: ci

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{matrix.os}}

    env:
      RUST_BACKTRACE: full
      RUSTFLAGS: -D warnings

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy

      - name: Clippy
        run: cargo clippy --all-targets

      - name: Test
        run: cargo test --all-targets
